#!/bin/bash

#"Help" page
if [ "$1" == "-h" ]; then
  echo "psst...just run me"
  echo "No shellcode--I promise"
  exit 0
fi


# A simple script to sandbox for a pentest

echo ------------------------------------------------------
echo -----------//AutoROE//-----------------------------
echo ------------------------------------------------------
echo "Save your insurance for the low-reliability exploits!"
echo ------------------------------------------------------
echo "I am meant for external assessments"
iptables-save > /etc/network/iptables.rules
echo "How many IP ranges?"
read numrange
echo ------------------------------------------------------
echo "Note: Specify ip range as 192.168.1.100-192.168.1.200"
echo "You may also enter a single address"
echo ------------------------------------------------------
counter=1
let numrange=numrange+1
# Allows for multiple ranges
while [ $counter -lt $numrange ]; do
	echo "What is your target IP range ("$counter")"
	read range
	iptables -A OUTPUT -m iprange --dst-range $range -j ACCEPT
	let counter=counter+1
done

echo ------------------------------------------------------
read -p "Autodetect IP [not for VPN connections](y/n) ?" autodetect
echo ------------------------------------------------------
if [[ "$autodetect" =~ ^([yY][eE][sS]|[yY])+$ ]]
then 
	#Potentially unsafe depending on networking
	#Unblock x.x.x.0,1,255
	ipaddr=$(hostname -I | awk -F'.' '{print $1,$2,$3}' OFS='.')
	iptables -A OUTPUT -m iprange --dst-range $ipaddr".0" -j ACCEPT
	iptables -A OUTPUT -m iprange --dst-range $ipaddr".1" -j ACCEPT
	iptables -A OUTPUT -m iprange --dst-range $ipaddr".255" -j ACCEPT
else
	#Safe Version
	iptables -A OUTPUT -m iprange --dst-range 10.0.0.0-10.255.255.255 -j ACCEPT
	iptables -A OUTPUT -m iprange --dst-range 172.16.0.0-172.32.255.255 -j ACCEPT
	iptables -A OUTPUT -m iprange --dst-range 192.168.0.0-192.168.255.255 -j ACCEPT
fi
# Deny all outbound traffic outside ranges
iptables -A OUTPUT -j DROP
# Flush/Restore
echo ------------------------------------------------------
read -p "Type anything to flush rules and restore Kali (not ctrl-c): " junkvar
iptables --flush
iptables-restore < /etc/network/iptables.rules
echo Done!

